### ISSUE TITLE
API endpoint to classify an emotion

### ISSUE THREAD

**Issue by andyAndyA** [andyAndyA/Speech-Emotion-Analytics-API#4]
I would like to: Build an API endpoint to classify a emotion (using the demo project files)

So that I can: Test the deployment of the sample demo project

**Comment by andyAndyA** [comment]
The following API endpoint being developed should conform to test-driven development (TDD) using Mocha.js and Chai.js. It should accept an input audio file with speech and output the emotion classified from that file.

**Comment by andyAndyA** [comment]
Use the [python-shell](https://www.npmjs.com/package/python-shell) NPM module to handle communication between Python and Node.js, to perform the SER processing.

**Comment by andyAndyA** [comment]
# Development Note
**Endpoint**: `/analyse/demo`

**Description**: Send an audio file with speech and get the most probable emotion shown back (done via Support Vector Machine Classification)

**Input**:
* *file* - Audio file to send
* *demoCode* - String passcode required to use this API endpoint, defined inside the implementation

**Output**:
* *string* - Classified emotion

**Test Cases**:
* Should be able to send an audio file and get a classified emotion back
* Should give error if video file was sent
* Should give error if other file types were sent
* Should give error if no file given
* Should give error if invalid demoCode given
* Should give error if no demoCode given

**Comment by andyAndyA** [comment]
Use Swagger's built-in [File Upload](https://swagger.io/docs/specification/2-0/file-upload/) support for handling input audio files.

**Comment by andyAndyA** [comment]
Currently dealing with an issue with running the Python script for performing the demo SER, using the python-shell module. The issue relates to the Python executable being unable to import the associated Python libraries in the script.

```
Uncaught Error: ImportError: DLL load failed: The specified module could not be found.
	at PythonShell.parseError
	at terminateIfNeeded
	at ChildProcess.<anonymous>
	at ChildProcess.EventEmitter.emit (domain.js:460:23)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

**Comment by andyAndyA** [comment]
Done in [endpoint-classify-emotion](https://github.com/andyAndyA/Speech-Emotion-Analytics-API/tree/endpoint-classify-emotion) branch.
